{{- $bridge := index .Values.services "bridge" }}
{{- if and $bridge $bridge.enabled }}
{{- $servers := list }}
{{- range $id, $service := .Values.services }}
{{- if and $service.enabled (eq $service.role "proxy") }}
{{- $name := include "xrproxy.serviceName" (dict "root" $ "id" $id) }}
{{- $servers = append $servers (dict "url" (printf "http://%s:%v" $name $service.port)) }}
{{- end }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xrproxy.fullname" . }}-downstreams
  labels:
    {{- include "xrproxy.labels" . | nindent 4 }}
data:
  downstreams.json: |-
    {{- dict "servers" $servers | toPrettyJson | nindent 4 }}
{{- end }}
