{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "xrproxy.fullname" . }}-default-deny-ingress
  labels:
    {{- include "xrproxy.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "xrproxy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "xrproxy.fullname" . }}-bridge-ingress
  labels:
    {{- include "xrproxy.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "xrproxy.selectorLabels" (dict "root" . "id" "bridge") | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: {{ (index .Values.services "bridge").port }}
          protocol: TCP
{{- if and .Values.gateway.enabled .Values.gateway.create }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "xrproxy.fullname" . }}-gateway-ingress
  labels:
    {{- include "xrproxy.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: {{ include "xrproxy.fullname" . }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: {{ default (ternary 443 80 .Values.gateway.listener.tls.enabled) .Values.gateway.listener.port }}
          protocol: TCP
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "xrproxy.fullname" . }}-downstream-ingress
  labels:
    {{- include "xrproxy.labels" . | nindent 4 }}
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - {{ include "xrproxy.name" . }}
      - key: app.kubernetes.io/instance
        operator: In
        values:
          - {{ .Release.Name }}
      - key: app.kubernetes.io/component
        operator: NotIn
        values:
          - bridge
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "xrproxy.selectorLabels" (dict "root" . "id" "bridge") | nindent 14 }}
{{- end }}
